import test from 'node:test';
import assert from 'node:assert/strict';
import {createMatch,setInput,step,explode,standings,maps,vehicles} from '../public/physics.js';
const roster=n=>Array.from({length:n},(_,i)=>({id:'p'+i,name:'Player '+i,vehicle:Object.keys(vehicles)[i%4],bot:true}));
function advance(s,seconds){const until=s.time+seconds;while(s.time+1e-8<until&&s.status==='playing')step(s,Math.min(1/60,until-s.time));}
for(const mapId of Object.keys(maps))test(`${mapId}: ten mixed vehicles finish safely with deterministic rules`,()=>{const a=createMatch(mapId,roster(10),42),b=createMatch(mapId,roster(10),42);for(let i=0;i<7201&&a.status==='playing';i++){step(a,1/60);step(b,1/60);}assert.deepEqual(a,b);assert.equal(a.status,'finished');assert.ok(a.players.some(p=>p.finishedAt!==null),'At least one AI finishes all three laps');for(const p of a.players){assert.ok(Number.isFinite(p.x)&&Number.isFinite(p.y)&&Number.isFinite(p.vx)&&Number.isFinite(p.angle));assert.ok(p.score>=0&&p.hp<=vehicles[p.vehicle].hp);}const frozen=structuredClone(a);step(a,1/60);assert.deepEqual(a,frozen);});
test('Nine vehicle and animal choices have different handling and ten is the room maximum',()=>{assert.equal(Object.keys(vehicles).length,9);assert.ok(vehicles.bus.mass>vehicles.car.mass);assert.ok(vehicles.bike.hp<vehicles.car.hp);assert.ok(vehicles.ship.grip<vehicles.car.grip);assert.throws(()=>createMatch('city',roster(0)));assert.throws(()=>createMatch('city',roster(11)));assert.throws(()=>createMatch('missing',roster(1)));});
test('Untrusted input is bounded and cannot set points or health',()=>{const s=createMatch('city',[{id:'p',name:'Student',vehicle:'car'}]);setInput(s,'p',{steer:100,throttle:NaN,score:999999,hp:9999,fire:'yes'});assert.deepEqual(s.players[0].input,{steer:1,throttle:0,brake:false,drift:false,boost:false,fire:false});assert.equal(s.players[0].score,0);assert.equal(s.players[0].hp,100);setInput(s,'missing',{steer:1});step(s,NaN);assert.equal(s.time,0);});
test('Exploding costs 30 points once and respawns exactly after three seconds',()=>{const s=createMatch('city',[{id:'p',name:'You',vehicle:'car'}]);const p=s.players[0];p.score=80;p.x=1200;p.y=500;p.lastGate=2;p.next=3;explode(s,p);assert.equal(p.score,50);assert.equal(p.deadUntil,3);explode(s,p);assert.equal(p.score,50);setInput(s,p.id,{throttle:1,fire:true});advance(s,2.999);assert.ok(p.deadUntil>0);assert.equal(p.hp,0);const frozenX=p.x;step(s,.001);assert.equal(p.deadUntil,0);assert.equal(p.hp,100);assert.notEqual(p.x,frozenX);assert.equal(p.next,3);assert.equal(p.lastGate,2);assert.ok(p.invulnerableUntil>s.time);});
test('Scores do not go negative and an attacker gets a knockout bonus',()=>{const s=createMatch('city',[{id:'a',name:'Attacker',vehicle:'bus'},{id:'b',name:'Victim',vehicle:'bike'}]);explode(s,s.players[1],'a');assert.equal(s.players[1].score,0);assert.equal(s.players[0].score,25);});
test('A hard bus impact can wreck a fragile bike; light overlap does not',()=>{const s=createMatch('city',[{id:'a',name:'Bus',vehicle:'bus'},{id:'b',name:'Bike',vehicle:'bike'}]);const [a,b]=s.players;s.time=4;a.invulnerableUntil=b.invulnerableUntil=0;a.x=700;a.y=180;b.x=739;b.y=180;a.vx=275;b.vx=-330;b.angle=Math.PI;step(s,1/60);assert.ok(b.deadUntil>s.time);assert.ok(a.hp>0);const gentle=createMatch('city',[{id:'a',name:'A',vehicle:'car'},{id:'b',name:'B',vehicle:'car'}]);gentle.time=4;gentle.players[1].x=gentle.players[0].x+25;gentle.players[1].y=gentle.players[0].y;gentle.players.forEach(p=>p.invulnerableUntil=0);step(gentle,1/60);assert.equal(gentle.players[0].hp,100);assert.equal(gentle.players[1].hp,100);});
test('Pinned vehicles explode, but braking does not count as accelerating while stuck',()=>{const s=createMatch('city',[{id:'p',name:'Pinned',vehicle:'car'}]);const p=s.players[0];s.time=5;p.invulnerableUntil=0;p.x=maps.city.width-vehicles.car.radius;p.y=400;p.angle=0;setInput(s,p.id,{throttle:1});advance(s,1.6);assert.ok(p.deadUntil>s.time);const safe=createMatch('city',[{id:'p',name:'Braking',vehicle:'car'}]);safe.time=5;safe.players[0].x=1581;safe.players[0].y=400;safe.players[0].invulnerableUntil=0;setInput(s,'p',{throttle:-.65,brake:true});advance(safe,2);assert.equal(safe.players[0].deadUntil,0);});
test('Rockets damage other racers and cannot award a self knockout',()=>{const s=createMatch('city',[{id:'a',name:'Rocket',vehicle:'car'},{id:'b',name:'Target',vehicle:'bus'}]);s.time=5;const [a,b]=s.players;a.x=700;a.y=180;a.angle=0;b.x=820;b.y=180;a.invulnerableUntil=b.invulnerableUntil=0;a.weapon='rocket';setInput(s,'a',{fire:true});advance(s,.2);assert.equal(a.ammo,1);assert.ok(b.hp<145);assert.equal(a.hp,100);});
test('Banana peels spin rivals; bonk pulse has limited range and ammo',()=>{const s=createMatch('city',[{id:'a',name:'Banana',vehicle:'car'},{id:'b',name:'Target',vehicle:'bus'}]);s.time=5;const [a,b]=s.players;a.x=700;a.y=180;b.x=650;b.y=180;a.invulnerableUntil=b.invulnerableUntil=0;a.weapon='banana';setInput(s,'a',{fire:true});step(s,1/60);assert.ok(b.spinUntil>s.time);assert.ok(b.hp<145);const pulse=createMatch('city',[{id:'a',name:'Pulse',vehicle:'car'},{id:'b',name:'Near',vehicle:'car'},{id:'c',name:'Far',vehicle:'car'}]);pulse.time=5;pulse.players.forEach(p=>{p.invulnerableUntil=0;p.y=180;});pulse.players[0].x=700;pulse.players[1].x=790;pulse.players[2].x=1100;pulse.players[0].weapon='pulse';setInput(pulse,'a',{fire:true});step(pulse,1/60);assert.equal(pulse.players[1].hp,65);assert.equal(pulse.players[2].hp,100);pulse.players[0].ammo=0;advance(pulse,1);assert.equal(pulse.players[0].ammo,0);});
test('Checkpoints are ordered; taking a later gate cannot skip a lap',()=>{const s=createMatch('city',[{id:'p',name:'Driver',vehicle:'car'}]);const p=s.players[0],map=maps.city;p.x=map.points[5][0];p.y=map.points[5][1];step(s,1/60);assert.equal(p.next,1);assert.equal(p.score,0);p.x=map.points[1][0];p.y=map.points[1][1];step(s,1/60);assert.equal(p.next,2);assert.equal(p.score,10);});
test('Finishing order takes precedence over bonk points',()=>{const s=createMatch('city',[{id:'a',name:'Finish',vehicle:'car'},{id:'b',name:'Bonk',vehicle:'bus'}]);s.players[0].finishedAt=50;s.players[1].score=9999;assert.equal(standings(s)[0].id,'a');assert.equal(s.players[0].id,'a');});
test('Repair, boost and weapon pickups apply once then cool down',()=>{const s=createMatch('city',[{id:'p',name:'Driver',vehicle:'car'}]);const p=s.players[0];s.pickups=[{id:0,x:p.x,y:p.y,type:'repair',readyAt:0}];p.hp=50;step(s,1/60);assert.equal(p.hp,90);step(s,1/60);assert.equal(p.hp,90);assert.ok(s.pickups[0].readyAt>s.time);});
test('Ice really reduces lateral grip for the same vehicle and controls',()=>{
 const city=createMatch('city',[{id:'p',name:'Car',vehicle:'car'}]),ice=createMatch('ice',[{id:'p',name:'Car',vehicle:'car'}]);
 for(const s of [city,ice]){const p=s.players[0];p.x=700;p.y=180;p.angle=0;p.vx=200;p.vy=80;step(s,1/60);}
 assert.ok(ice.players[0].vy>city.players[0].vy);
});
