// CPU projection of the actual renderer's triangle buffer for geometry inspection.
// This checks meshes and camera framing; it does not replace testing WebGL on a phone.
import {Renderer3D} from '../public/three-d.js';import {createMatch} from '../public/physics.js';import {createCanvas} from '@napi-rs/canvas';import {writeFileSync} from 'node:fs';
let data,matrix;const gl=new Proxy({getShaderParameter:()=>true,getProgramParameter:()=>true,getAttribLocation:()=>0,getUniformLocation:(_,name)=>name,bufferData:(_,v)=>data=v,uniformMatrix4fv:(_,__,m)=>matrix=m},{get:(o,k)=>k in o?o[k]:(()=>{})});
const canvas={width:1280,height:720,getContext:()=>gl,addEventListener:()=>{}};const s=createMatch('beach',[{id:'you',vehicle:process.argv[2]||'car'}],42,{mode:'scenic'});s.players[0].x=1400;s.players[0].y=550+Math.sin(1400/1800)*210+Math.sin(1400/4300)*160;new Renderer3D(canvas).draw(s,'you',{camera:{height:60,distance:100},dt:.016});
const out=createCanvas(1280,720),c=out.getContext('2d'),gradient=c.createLinearGradient(0,0,0,720);gradient.addColorStop(0,'#82cadd');gradient.addColorStop(1,'#e9ecdb');c.fillStyle=gradient;c.fillRect(0,0,1280,720);const triangles=[];
function project(i){const p=[data[i],data[i+1],data[i+2],1],v=[0,0,0,0];for(let r=0;r<4;r++)for(let k=0;k<4;k++)v[r]+=matrix[k*4+r]*p[k];if(v[3]<2)return null;return{x:(v[0]/v[3]+1)*640,y:(1-v[1]/v[3])*360,z:v[3]};}
for(let i=0;i<data.length;i+=30){const points=[project(i),project(i+10),project(i+20)];if(points.some(p=>!p))continue;const normal=[data[i+3],data[i+4],data[i+5]],light=.62+.38*Math.max(0,(-.4*normal[0]+normal[1]+.3*normal[2])/Math.sqrt(1.25)),z=points.reduce((n,p)=>n+p.z,0)/3,mist=Math.max(0,Math.min(1,(z-1800)/5700)),sky=[.59,.86,.91],color=[6,7,8].map((j,k)=>Math.round((data[i+j]*light*(1-mist)+sky[k]*mist)*255));triangles.push({points,z,color});}
const image=c.getImageData(0,0,1280,720),depth=new Float32Array(1280*720).fill(Infinity);for(const {points,color} of triangles){const [a,b,d]=points,minX=Math.max(0,Math.floor(Math.min(a.x,b.x,d.x))),maxX=Math.min(1279,Math.ceil(Math.max(a.x,b.x,d.x))),minY=Math.max(0,Math.floor(Math.min(a.y,b.y,d.y))),maxY=Math.min(719,Math.ceil(Math.max(a.y,b.y,d.y))),den=(b.y-d.y)*(a.x-d.x)+(d.x-b.x)*(a.y-d.y);if(Math.abs(den)<.00001)continue;for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++){const u=((b.y-d.y)*(x-d.x)+(d.x-b.x)*(y-d.y))/den,v=((d.y-a.y)*(x-d.x)+(a.x-d.x)*(y-d.y))/den,w=1-u-v;if(u<0||v<0||w<0)continue;const z=1/(u/a.z+v/b.z+w/d.z),index=y*1280+x;if(z>=depth[index])continue;depth[index]=z;image.data[index*4]=color[0];image.data[index*4+1]=color[1];image.data[index*4+2]=color[2];image.data[index*4+3]=255;}}c.putImageData(image,0,0);writeFileSync(`docs/previews/${process.argv[2]||'car'}-geometry.png`,out.toBuffer('image/png'));console.log(`Projected ${triangles.length} triangles from the actual 3D mesh and camera with depth testing.`);
